### ISSUE TITLE
Training on my own dataset

### ISSUE THREAD

**Issue by leelbc** [Jiaxuan-Li/MGU-Net#2]
(MGU-Net-main) E:\_BACKUP\lbc\MGU-Net-main>python main_ts.py --name tsmgunet -d ./data/dataset --batch-size 1 --epoch 50 --lr 0.001
torch version: 1.10.0
Total amount of train images is : 96
Total amount of eval images is : 96
Total amount of test images is : 96
data_dir : ./data/dataset
name : tsmgunet
workers : 2
step : 20
batch_size : 1
epochs : 50
lr : 0.001
lr_mode : step
momentum : 0.9
weight_decay : 0.0001
t : t1
model_path :
############### tsmgunet ###############
[2021-12-03 04:27:43,359 main_ts.py:278 train_seg] Epoch: [0]
Traceback (most recent call last):
  File "main_ts.py", line 394, in <module>
    main()
  File "main_ts.py", line 386, in main
    train_seg(args,train_result_path,train_loader,eval_loader)
  File "main_ts.py", line 280, in train_seg
    loss,dice_train,dice_1,dice_2,dice_3,dice_4,dice_5,dice_6,dice_7,dice_8,dice_9,dice_10 = train(args,train_loader, model,criterion1, criterion2, optimizer,epoch)
  File "main_ts.py", line 53, in train
    output_seg1,_,output_seg = model(input_var1)
  File "E:\anaconda\envs\MGU-Net-main\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\anaconda\envs\MGU-Net-main\lib\site-packages\torch\nn\parallel\data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "E:\anaconda\envs\MGU-Net-main\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\_BACKUP\lbc\MGU-Net-main\models\nets\TSNet.py", line 16, in forward
    out1 = self.stage1(inputs)
  File "E:\anaconda\envs\MGU-Net-main\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\_BACKUP\lbc\MGU-Net-main\models\nets\MGUNet.py", line 106, in forward
    up3 = self.up_concat3(center, conv3)
  File "E:\anaconda\envs\MGU-Net-main\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\_BACKUP\lbc\MGU-Net-main\models\utils\utils.py", line 91, in forward
    outputs0 = torch.cat([outputs0,input[i]], 1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 52 but got size 53 for tensor number 1 in the list.
I would like to ask what went wrong

**Comment by Jiaxuan-Li** [comment]
The size of the input image should be 1024 × 992.

**Comment by leelbc** [comment]
> The size of the input image should be 1024 × 992.

I would like to ask where should I change the input size if I want to change it, like the size of the duke dataset is different from the collected dataset by yourself

**Comment by Jiaxuan-Li** [comment]
You could resize the image in your dataset, I resized the image in the Duke dataset into 496× 496.

**Comment by leelbc** [comment]
> You could resize the image in your dataset, I resized the image in the Duke dataset into 496× 496.

Thx very much, I'll try it, 
Kind,
